const {webkit,chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.QURAN_TEST_BASE||'http://127.0.0.1:8871';const data=JSON.parse(fs.readFileSync('quran/data/hadith-deema.json'));const results=[];
async function auth(page,assigned='quran-deema'){await page.addInitScript(id=>{window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:'hadith-fixture'}}}}),onAuthStateChange(cb){window.logoutFixture=cb;}},from:()=>({select(){return this},eq(k,v){if(k==='quiz_id')this.id=v;return this},async maybeSingle(){return {data:this.id===id?{quiz_id:id}:null}}})})}},assigned)}
(async()=>{
for(const [name,w,h,type] of [['small',320,568,webkit],['iphone-small',375,548,webkit],['iphone',390,664,webkit],['ipad',820,1180,webkit],['desktop',1440,1000,chromium]]){
 const browser=await type.launch(),page=await browser.newPage({viewport:{width:w,height:h}});await auth(page);await page.route('https://api.quran.com/**',r=>r.abort());
 await page.goto(base+'/quran/?group=deema');await page.locator('#hadithSection').waitFor({state:'visible'});assert.equal(await page.locator('#hadithSection a').count(),1);assert.equal(await page.locator('#surahList a').count(),2);
 async function fits(){const b=await page.evaluate(()=>({w:innerWidth,h:innerHeight,sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight}));assert(b.sw<=b.w,JSON.stringify(b));if(w<721)assert(b.sh<=b.h+1,JSON.stringify(b));}
 await fits();await page.locator('.hadith-card').click();await page.locator('#hadithReader').waitFor({state:'visible'});await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('#hadithText').textContent(),data.text);await fits();
 const bounds=await page.locator('#hadithText').evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);const a=r.getBoundingClientRect(),b=e.parentElement.getBoundingClientRect();return a.top>=b.top&&a.bottom<=b.bottom&&a.left>=b.left&&a.right<=b.right});assert(bounds,name+' clipped text');
 await page.screenshot({path:'/tmp/hadith-'+name+'.png'});await page.locator('#hadithTest').click();assert(await page.locator('#hadithText').isHidden());await page.locator('#hadithReveal').click();assert(await page.locator('#hadithText').isVisible());await fits();
 results.push({name,noClippedText:true,noHorizontalScroll:true,noVerticalScroll:w<721});await browser.close();
}
const b=await webkit.launch(),p=await b.newPage();await auth(p);await p.goto(base+'/quran/hadith.html?group=deema');await p.locator('#hadithReader').waitFor({state:'visible'});
await p.addScriptTag({content:'window.mediaProof={ended:0}; const original=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){this.addEventListener("ended",()=>mediaProof.ended++);return original.call(this)};'});
await p.locator('#hadithTest').click();await p.locator('#hadithListen').click();await p.waitForFunction(()=>player&&!player.paused);assert(await p.locator('#hadithText').isHidden());await p.waitForFunction(()=>mediaProof.ended===1&&player===null,{},{timeout:30000});
await p.locator('#hadithListen').click();await p.waitForFunction(()=>player&&!player.paused);await p.locator('#hadithListen').click();assert(await p.evaluate(()=>player===null));
await p.route('**/hadith-raditu-v4.mp3',r=>r.abort());await p.locator('#hadithListen').click();await p.waitForFunction(()=>document.getElementById('hadithMessage').textContent.length>0&&player===null);await p.locator('#hadithReveal').click();assert(await p.locator('#hadithText').isVisible());
await p.evaluate(()=>logoutFixture('SIGNED_OUT',null));await p.waitForURL(base+'/');results.push({realV4MediaPlayback:true,hiddenTextStayedHidden:true,stopWorks:true,failureKeepsReading:true,signoutRedirects:true});await p.close();
const denied=await b.newPage();await auth(denied,'quran-al-balad');await denied.route('https://ahmad9077.github.io/quizzes-hub/**',r=>r.fulfill({body:'denied fixture'}));await denied.goto(base+'/quran/hadith.html?group=hamoud');await denied.waitForURL(u=>u.searchParams.get('access')==='unauthorized');results.push({hamoudCannotEnterHadith:true});await b.close();
fs.writeFileSync('docs/hadith-tests.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));})().catch(e=>{console.error(e);process.exit(1)});
