const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');const root=process.cwd();
(async()=>{const results=[];for(const [engine,type] of [['WebKit',webkit]]){const b=await type.launch({headless:true}),p=await b.newPage({viewport:{width:390,height:664}});
await p.addInitScript(()=>{window.proof={played:[],ended:[],active:0,max:0,hidden:[]};const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){const file=this.src.split('/').at(-1);proof.played.push(file);proof.hidden.push(document.getElementById('verseText').hidden);let active=false;this.addEventListener('playing',()=>{if(!active){active=true;proof.active++;proof.max=Math.max(proof.max,proof.active)}});const stop=()=>{if(active){active=false;proof.active--}};this.addEventListener('pause',stop);this.addEventListener('ended',()=>{proof.ended.push(file);stop()});return play.call(this)}});
await p.addInitScript(()=>{window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:'audio-fixture'}}}}),onAuthStateChange(){}},from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{quiz_id:'quran-al-balad'}})})})}});await p.goto((process.env.QURAN_TEST_BASE || 'http://127.0.0.1:8871')+'/quran/');await p.locator('.surah-card').click();await p.locator('#reader').waitFor({state:'visible'});await p.evaluate(()=>selectVerse(13));await p.locator('#listen').click();await p.waitForFunction(()=>proof.ended.length===1&&!playing,{},{timeout:30000});await p.waitForTimeout(800);const single=await p.evaluate(()=>structuredClone(proof));assert.deepStrictEqual(single.played,['090013.mp3']);assert.deepStrictEqual(single.ended,['090013.mp3']);assert(await p.locator('#playStatus').textContent()==='');
await p.locator('#testMode').click();await p.evaluate(()=>{selectVerse(3);proof.played=[];proof.ended=[];proof.hidden=[]});await p.locator('#listenUntil').click();await p.waitForFunction(()=>proof.ended.length===4&&!playing,{},{timeout:60000});const cumulative=await p.evaluate(()=>structuredClone(proof));assert.deepStrictEqual(cumulative.ended,['001001.mp3','090001.mp3','090002.mp3','090003.mp3']);assert(cumulative.hidden.every(Boolean));assert(cumulative.max===1);assert(await p.locator('#verseText').isHidden());
await p.locator('#listenUntil').click();await p.waitForFunction(()=>audioElement&&!audioElement.paused);await p.locator('#backHome').click();await p.locator('#home').waitFor({state:'visible'});const count=await p.evaluate(()=>proof.played.length);await p.waitForTimeout(800);assert(await p.evaluate(()=>!playing&&audioElement===null&&proof.played.length)===count);
await p.locator('.surah-card').click();await p.locator('#learnMode').click();await p.route('**/data/audio.json',r=>r.abort());await p.evaluate(()=>{delete catalog.get(90).audioData;audioData=null});await p.locator('#listen').click();await p.waitForFunction(()=>!playing&&document.getElementById('message').textContent.length>0);assert(await p.locator('#verseText').isVisible());
results.push({engine,singleVersePlayedOnce:single.ended,cumulativeUntil3:cumulative.ended,textStayedHidden:true,maxConcurrentPlayback:cumulative.max,homeStopsAudio:true,audioFailureKeepsReading:true,realMediaPlayback:true,physicalDevice:false});await b.close();console.log(engine+' passed')}
fs.writeFileSync(path.join(root,'docs/quran-real-audio-tests.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));})().catch(e=>{console.error(e.message);process.exit(1)});
