-- Seed adaptive question difficulty labels for world flag and country map quizzes.
-- Generated from the deployed quiz datasets. Difficulty is an initial 1-100 calibration.

insert into public.question_difficulty_profiles (quiz_id, question_key, difficulty, topic_tags)
values
  ('world-flags', 'AF', 37, array['flags', 'asia', 'southern_asia', 'standard_flag']),
  ('world-flags', 'AL', 40, array['flags', 'europe', 'southeast_europe', 'standard_flag']),
  ('world-flags', 'DZ', 56, array['flags', 'africa', 'northern_africa', 'lookalike_flag']),
  ('world-flags', 'AD', 58, array['flags', 'europe', 'southern_europe', 'lookalike_flag']),
  ('world-flags', 'AO', 56, array['flags', 'africa', 'middle_africa', 'lookalike_flag']),
  ('world-flags', 'AG', 48, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'AR', 24, array['flags', 'americas', 'south_america', 'standard_flag']),
  ('world-flags', 'AM', 55, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'AU', 46, array['flags', 'oceania', 'australia_and_new_zealand', 'lookalike_flag']),
  ('world-flags', 'AT', 58, array['flags', 'europe', 'central_europe', 'lookalike_flag']),
  ('world-flags', 'AZ', 37, array['flags', 'asia', 'western_asia', 'standard_flag']),
  ('world-flags', 'BS', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'BH', 55, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'BD', 55, array['flags', 'asia', 'southern_asia', 'lookalike_flag']),
  ('world-flags', 'BB', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'BY', 40, array['flags', 'europe', 'eastern_europe', 'standard_flag']),
  ('world-flags', 'BE', 58, array['flags', 'europe', 'western_europe', 'lookalike_flag']),
  ('world-flags', 'BZ', 36, array['flags', 'americas', 'central_america', 'standard_flag']),
  ('world-flags', 'BJ', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'BT', 55, array['flags', 'asia', 'southern_asia', 'lookalike_flag']),
  ('world-flags', 'BO', 54, array['flags', 'americas', 'south_america', 'lookalike_flag']),
  ('world-flags', 'BA', 44, array['flags', 'europe', 'southeast_europe', 'standard_flag']),
  ('world-flags', 'BW', 56, array['flags', 'africa', 'southern_africa', 'lookalike_flag']),
  ('world-flags', 'BR', 24, array['flags', 'americas', 'south_america', 'standard_flag']),
  ('world-flags', 'BN', 37, array['flags', 'asia', 'south_eastern_asia', 'standard_flag']),
  ('world-flags', 'BG', 40, array['flags', 'europe', 'southeast_europe', 'standard_flag']),
  ('world-flags', 'BF', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'BI', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'CV', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'KH', 37, array['flags', 'asia', 'south_eastern_asia', 'standard_flag']),
  ('world-flags', 'CM', 56, array['flags', 'africa', 'middle_africa', 'lookalike_flag']),
  ('world-flags', 'CA', 24, array['flags', 'americas', 'north_america', 'standard_flag']),
  ('world-flags', 'CF', 42, array['flags', 'africa', 'middle_africa', 'standard_flag']),
  ('world-flags', 'TD', 56, array['flags', 'africa', 'middle_africa', 'lookalike_flag']),
  ('world-flags', 'CL', 54, array['flags', 'americas', 'south_america', 'lookalike_flag']),
  ('world-flags', 'CN', 25, array['flags', 'asia', 'eastern_asia', 'standard_flag']),
  ('world-flags', 'CO', 54, array['flags', 'americas', 'south_america', 'lookalike_flag']),
  ('world-flags', 'KM', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'CR', 54, array['flags', 'americas', 'central_america', 'lookalike_flag']),
  ('world-flags', 'CI', 56, array['flags', 'africa', 'western_africa', 'lookalike_flag']),
  ('world-flags', 'HR', 58, array['flags', 'europe', 'southeast_europe', 'lookalike_flag']),
  ('world-flags', 'CU', 62, array['flags', 'americas', 'caribbean', 'lookalike_flag']),
  ('world-flags', 'CY', 40, array['flags', 'europe', 'southern_europe', 'standard_flag']),
  ('world-flags', 'CZ', 40, array['flags', 'europe', 'central_europe', 'standard_flag']),
  ('world-flags', 'CD', 42, array['flags', 'africa', 'middle_africa', 'standard_flag']),
  ('world-flags', 'DK', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'DJ', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'DM', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'DO', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'EC', 54, array['flags', 'americas', 'south_america', 'lookalike_flag']),
  ('world-flags', 'EG', 44, array['flags', 'africa', 'northern_africa', 'lookalike_flag']),
  ('world-flags', 'SV', 54, array['flags', 'americas', 'central_america', 'lookalike_flag']),
  ('world-flags', 'GQ', 38, array['flags', 'africa', 'middle_africa', 'standard_flag']),
  ('world-flags', 'ER', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'EE', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'SZ', 38, array['flags', 'africa', 'southern_africa', 'standard_flag']),
  ('world-flags', 'ET', 56, array['flags', 'africa', 'eastern_africa', 'lookalike_flag']),
  ('world-flags', 'FJ', 58, array['flags', 'oceania', 'melanesia', 'lookalike_flag']),
  ('world-flags', 'FI', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'FR', 28, array['flags', 'europe', 'western_europe', 'standard_flag']),
  ('world-flags', 'GA', 38, array['flags', 'africa', 'middle_africa', 'standard_flag']),
  ('world-flags', 'GM', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'GE', 55, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'DE', 46, array['flags', 'europe', 'western_europe', 'lookalike_flag']),
  ('world-flags', 'GH', 56, array['flags', 'africa', 'western_africa', 'lookalike_flag']),
  ('world-flags', 'GR', 40, array['flags', 'europe', 'southern_europe', 'standard_flag']),
  ('world-flags', 'GD', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'GT', 54, array['flags', 'americas', 'central_america', 'lookalike_flag']),
  ('world-flags', 'GN', 56, array['flags', 'africa', 'western_africa', 'lookalike_flag']),
  ('world-flags', 'GW', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'GY', 36, array['flags', 'americas', 'south_america', 'standard_flag']),
  ('world-flags', 'HT', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'HN', 54, array['flags', 'americas', 'central_america', 'lookalike_flag']),
  ('world-flags', 'HU', 40, array['flags', 'europe', 'central_europe', 'standard_flag']),
  ('world-flags', 'IS', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'IN', 25, array['flags', 'asia', 'southern_asia', 'standard_flag']),
  ('world-flags', 'ID', 55, array['flags', 'asia', 'south_eastern_asia', 'lookalike_flag']),
  ('world-flags', 'IR', 37, array['flags', 'asia', 'southern_asia', 'standard_flag']),
  ('world-flags', 'IQ', 55, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'IE', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'IL', 37, array['flags', 'asia', 'western_asia', 'standard_flag']),
  ('world-flags', 'IT', 46, array['flags', 'europe', 'southern_europe', 'lookalike_flag']),
  ('world-flags', 'JM', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'JP', 43, array['flags', 'asia', 'eastern_asia', 'lookalike_flag']),
  ('world-flags', 'JO', 37, array['flags', 'asia', 'western_asia', 'standard_flag']),
  ('world-flags', 'KZ', 37, array['flags', 'asia', 'central_asia', 'standard_flag']),
  ('world-flags', 'KE', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'KI', 50, array['flags', 'oceania', 'micronesia', 'standard_flag']),
  ('world-flags', 'XK', 40, array['flags', 'europe', 'southeast_europe', 'standard_flag']),
  ('world-flags', 'KW', 43, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'KG', 37, array['flags', 'asia', 'central_asia', 'standard_flag']),
  ('world-flags', 'LA', 55, array['flags', 'asia', 'south_eastern_asia', 'lookalike_flag']),
  ('world-flags', 'LV', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'LB', 55, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'LS', 56, array['flags', 'africa', 'southern_africa', 'lookalike_flag']),
  ('world-flags', 'LR', 56, array['flags', 'africa', 'western_africa', 'lookalike_flag']),
  ('world-flags', 'LY', 38, array['flags', 'africa', 'northern_africa', 'standard_flag']),
  ('world-flags', 'LI', 40, array['flags', 'europe', 'western_europe', 'standard_flag']),
  ('world-flags', 'LT', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'LU', 58, array['flags', 'europe', 'western_europe', 'lookalike_flag']),
  ('world-flags', 'MG', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'MW', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'MY', 55, array['flags', 'asia', 'south_eastern_asia', 'lookalike_flag']),
  ('world-flags', 'MV', 37, array['flags', 'asia', 'southern_asia', 'standard_flag']),
  ('world-flags', 'ML', 56, array['flags', 'africa', 'western_africa', 'lookalike_flag']),
  ('world-flags', 'MT', 40, array['flags', 'europe', 'southern_europe', 'standard_flag']),
  ('world-flags', 'MH', 50, array['flags', 'oceania', 'micronesia', 'standard_flag']),
  ('world-flags', 'MR', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'MU', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'MX', 24, array['flags', 'americas', 'north_america', 'standard_flag']),
  ('world-flags', 'FM', 50, array['flags', 'oceania', 'micronesia', 'standard_flag']),
  ('world-flags', 'MD', 58, array['flags', 'europe', 'eastern_europe', 'lookalike_flag']),
  ('world-flags', 'MC', 58, array['flags', 'europe', 'western_europe', 'lookalike_flag']),
  ('world-flags', 'MN', 37, array['flags', 'asia', 'eastern_asia', 'standard_flag']),
  ('world-flags', 'ME', 40, array['flags', 'europe', 'southeast_europe', 'standard_flag']),
  ('world-flags', 'MA', 56, array['flags', 'africa', 'northern_africa', 'lookalike_flag']),
  ('world-flags', 'MZ', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'MM', 55, array['flags', 'asia', 'south_eastern_asia', 'lookalike_flag']),
  ('world-flags', 'NA', 38, array['flags', 'africa', 'southern_africa', 'standard_flag']),
  ('world-flags', 'NR', 50, array['flags', 'oceania', 'micronesia', 'standard_flag']),
  ('world-flags', 'NP', 55, array['flags', 'asia', 'southern_asia', 'lookalike_flag']),
  ('world-flags', 'NL', 58, array['flags', 'europe', 'western_europe', 'lookalike_flag']),
  ('world-flags', 'NZ', 58, array['flags', 'oceania', 'australia_and_new_zealand', 'lookalike_flag']),
  ('world-flags', 'NI', 54, array['flags', 'americas', 'central_america', 'lookalike_flag']),
  ('world-flags', 'NE', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'NG', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'KP', 37, array['flags', 'asia', 'eastern_asia', 'standard_flag']),
  ('world-flags', 'MK', 40, array['flags', 'europe', 'southeast_europe', 'standard_flag']),
  ('world-flags', 'NO', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'OM', 37, array['flags', 'asia', 'western_asia', 'standard_flag']),
  ('world-flags', 'PK', 55, array['flags', 'asia', 'southern_asia', 'lookalike_flag']),
  ('world-flags', 'PW', 68, array['flags', 'oceania', 'micronesia', 'lookalike_flag']),
  ('world-flags', 'PS', 37, array['flags', 'asia', 'western_asia', 'standard_flag']),
  ('world-flags', 'PA', 54, array['flags', 'americas', 'central_america', 'lookalike_flag']),
  ('world-flags', 'PG', 40, array['flags', 'oceania', 'melanesia', 'standard_flag']),
  ('world-flags', 'PY', 54, array['flags', 'americas', 'south_america', 'lookalike_flag']),
  ('world-flags', 'PE', 54, array['flags', 'americas', 'south_america', 'lookalike_flag']),
  ('world-flags', 'PH', 37, array['flags', 'asia', 'south_eastern_asia', 'standard_flag']),
  ('world-flags', 'PL', 58, array['flags', 'europe', 'central_europe', 'lookalike_flag']),
  ('world-flags', 'PT', 40, array['flags', 'europe', 'southern_europe', 'standard_flag']),
  ('world-flags', 'QA', 43, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'CG', 42, array['flags', 'africa', 'middle_africa', 'standard_flag']),
  ('world-flags', 'RO', 58, array['flags', 'europe', 'southeast_europe', 'lookalike_flag']),
  ('world-flags', 'RU', 46, array['flags', 'europe', 'eastern_europe', 'lookalike_flag']),
  ('world-flags', 'RW', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'KN', 48, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'LC', 44, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'VC', 48, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'WS', 50, array['flags', 'oceania', 'polynesia', 'standard_flag']),
  ('world-flags', 'SM', 40, array['flags', 'europe', 'southern_europe', 'standard_flag']),
  ('world-flags', 'ST', 42, array['flags', 'africa', 'middle_africa', 'standard_flag']),
  ('world-flags', 'SA', 25, array['flags', 'asia', 'western_asia', 'standard_flag']),
  ('world-flags', 'SN', 56, array['flags', 'africa', 'western_africa', 'lookalike_flag']),
  ('world-flags', 'RS', 58, array['flags', 'europe', 'southeast_europe', 'lookalike_flag']),
  ('world-flags', 'SC', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'SL', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'SG', 55, array['flags', 'asia', 'south_eastern_asia', 'lookalike_flag']),
  ('world-flags', 'SK', 58, array['flags', 'europe', 'central_europe', 'lookalike_flag']),
  ('world-flags', 'SI', 58, array['flags', 'europe', 'central_europe', 'lookalike_flag']),
  ('world-flags', 'SB', 40, array['flags', 'oceania', 'melanesia', 'standard_flag']),
  ('world-flags', 'SO', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'ZA', 26, array['flags', 'africa', 'southern_africa', 'standard_flag']),
  ('world-flags', 'KR', 25, array['flags', 'asia', 'eastern_asia', 'standard_flag']),
  ('world-flags', 'SS', 38, array['flags', 'africa', 'middle_africa', 'standard_flag']),
  ('world-flags', 'ES', 28, array['flags', 'europe', 'southern_europe', 'standard_flag']),
  ('world-flags', 'LK', 55, array['flags', 'asia', 'southern_asia', 'lookalike_flag']),
  ('world-flags', 'SD', 56, array['flags', 'africa', 'northern_africa', 'lookalike_flag']),
  ('world-flags', 'SR', 36, array['flags', 'americas', 'south_america', 'standard_flag']),
  ('world-flags', 'SE', 58, array['flags', 'europe', 'northern_europe', 'lookalike_flag']),
  ('world-flags', 'CH', 58, array['flags', 'europe', 'western_europe', 'lookalike_flag']),
  ('world-flags', 'SY', 55, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'TJ', 37, array['flags', 'asia', 'central_asia', 'standard_flag']),
  ('world-flags', 'TZ', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'TH', 55, array['flags', 'asia', 'south_eastern_asia', 'lookalike_flag']),
  ('world-flags', 'TL', 37, array['flags', 'asia', 'south_eastern_asia', 'standard_flag']),
  ('world-flags', 'TG', 38, array['flags', 'africa', 'western_africa', 'standard_flag']),
  ('world-flags', 'TO', 50, array['flags', 'oceania', 'polynesia', 'standard_flag']),
  ('world-flags', 'TT', 48, array['flags', 'americas', 'caribbean', 'standard_flag']),
  ('world-flags', 'TN', 56, array['flags', 'africa', 'northern_africa', 'lookalike_flag']),
  ('world-flags', 'TR', 43, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'TM', 37, array['flags', 'asia', 'central_asia', 'standard_flag']),
  ('world-flags', 'TV', 68, array['flags', 'oceania', 'polynesia', 'lookalike_flag']),
  ('world-flags', 'UG', 56, array['flags', 'africa', 'eastern_africa', 'lookalike_flag']),
  ('world-flags', 'UA', 40, array['flags', 'europe', 'eastern_europe', 'standard_flag']),
  ('world-flags', 'AE', 47, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'GB', 28, array['flags', 'europe', 'northern_europe', 'standard_flag']),
  ('world-flags', 'US', 42, array['flags', 'americas', 'north_america', 'lookalike_flag']),
  ('world-flags', 'UY', 36, array['flags', 'americas', 'south_america', 'standard_flag']),
  ('world-flags', 'UZ', 37, array['flags', 'asia', 'central_asia', 'standard_flag']),
  ('world-flags', 'VU', 40, array['flags', 'oceania', 'melanesia', 'standard_flag']),
  ('world-flags', 'VA', 40, array['flags', 'europe', 'southern_europe', 'standard_flag']),
  ('world-flags', 'VE', 54, array['flags', 'americas', 'south_america', 'lookalike_flag']),
  ('world-flags', 'VN', 37, array['flags', 'asia', 'south_eastern_asia', 'standard_flag']),
  ('world-flags', 'YE', 55, array['flags', 'asia', 'western_asia', 'lookalike_flag']),
  ('world-flags', 'ZM', 38, array['flags', 'africa', 'eastern_africa', 'standard_flag']),
  ('world-flags', 'ZW', 38, array['flags', 'africa', 'southern_africa', 'standard_flag']),
  ('country-map', 'Afghanistan', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Albania', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Algeria', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Andorra', 74, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Angola', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Argentina', 18, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Armenia', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Australia', 18, array['map_outline', 'large_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'Austria', 60, array['map_outline', 'medium_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Azerbaijan', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Bangladesh', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Belarus', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Belgium', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Belize', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Benin', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Bhutan', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Bolivia', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Bosnia and Herzegovina', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Botswana', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Brazil', 24, array['map_outline', 'large_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Brunei', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Bulgaria', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Burkina Faso', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Burundi', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Cambodia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Cameroon', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Canada', 20, array['map_outline', 'large_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Central African Republic', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Chad', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Chile', 32, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'China', 18, array['map_outline', 'large_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Colombia', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Costa Rica', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Côte d''Ivoire', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Croatia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Cuba', 44, array['map_outline', 'medium_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'Czech Republic', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Democratic Republic of the Congo', 45, array['map_outline', 'medium_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Denmark', 62, array['map_outline', 'medium_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Djibouti', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Dominican Republic', 72, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'East Timor', 72, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Ecuador', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Egypt', 25, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'El Salvador', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Equatorial Guinea', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Eritrea', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Estonia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Eswatini', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Ethiopia', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Finland', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'France', 18, array['map_outline', 'large_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Gabon', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Gambia', 72, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Georgia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Germany', 34, array['map_outline', 'medium_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Ghana', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Greece', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Guatemala', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Guinea', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Guinea-Bissau', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Guyana', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Haiti', 72, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Honduras', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Hong Kong', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Hungary', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Iceland', 44, array['map_outline', 'medium_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'India', 18, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Indonesia', 26, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Iran', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Iraq', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Ireland', 59, array['map_outline', 'medium_outline', 'one_land_border', 'island_shape']),
  ('country-map', 'Italy', 25, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Japan', 23, array['map_outline', 'large_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'Jordan', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Kazakhstan', 32, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Kenya', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Kosovo', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Kuwait', 50, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Kyrgyzstan', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Laos', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Latvia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Lebanon', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Lesotho', 72, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Liberia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Libya', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Liechtenstein', 74, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Lithuania', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Luxembourg', 74, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Macao', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Macedonia', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Madagascar', 44, array['map_outline', 'medium_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'Malawi', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Malaysia', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Mali', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Mauritania', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Mexico', 18, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Moldova', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Monaco', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Mongolia', 32, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Montenegro', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Morocco', 47, array['map_outline', 'medium_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Mozambique', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Myanmar', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Namibia', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Nepal', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Netherlands', 26, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'New Zealand', 37, array['map_outline', 'large_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'Nicaragua', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Niger', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Nigeria', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'North Korea', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Norway', 32, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Oman', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Pakistan', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Palestine', 74, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Panama', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Papua New Guinea', 47, array['map_outline', 'medium_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Paraguay', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Peru', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Philippines', 44, array['map_outline', 'medium_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'Poland', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Portugal', 40, array['map_outline', 'large_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Qatar', 72, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Republic of the Congo', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Romania', 42, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Russia', 24, array['map_outline', 'large_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Rwanda', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'San Marino', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Saudi Arabia', 25, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Senegal', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Serbia', 60, array['map_outline', 'medium_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Siachen Glacier', 74, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Sierra Leone', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Sint Maarten', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Slovakia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Slovenia', 64, array['map_outline', 'small_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Somalia', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'South Africa', 18, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'South Korea', 62, array['map_outline', 'medium_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'South Sudan', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Spain', 18, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Sri Lanka', 69, array['map_outline', 'small_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'St-Martin', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Sudan', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Suriname', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Sweden', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Switzerland', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Syria', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Taiwan', 69, array['map_outline', 'small_outline', 'no_land_borders', 'island_shape']),
  ('country-map', 'Tajikistan', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Tanzania', 45, array['map_outline', 'medium_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Thailand', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Togo', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Tunisia', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Turkey', 31, array['map_outline', 'medium_outline', 'many_land_borders', 'border_shape']),
  ('country-map', 'Turkmenistan', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Uganda', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Ukraine', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'United Arab Emirates', 40, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'United Kingdom', 30, array['map_outline', 'medium_outline', 'one_land_border', 'island_shape']),
  ('country-map', 'United States', 18, array['map_outline', 'large_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Uruguay', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Uzbekistan', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Vatican', 82, array['map_outline', 'small_outline', 'one_land_border', 'border_shape']),
  ('country-map', 'Venezuela', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Vietnam', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Yemen', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Zambia', 39, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape']),
  ('country-map', 'Zimbabwe', 54, array['map_outline', 'medium_outline', 'some_land_borders', 'border_shape'])
on conflict (quiz_id, question_key) do update set
  difficulty = excluded.difficulty,
  topic_tags = excluded.topic_tags,
  updated_at = now();

select quiz_id, count(*) as labelled_questions, min(difficulty) as min_difficulty, max(difficulty) as max_difficulty
from public.question_difficulty_profiles
where quiz_id in ('world-flags', 'country-map')
group by quiz_id
order by quiz_id;
