-- Register English Word Choice Quiz and seed adaptive question profiles.
-- Generated from english-word-choice-quiz src/data/wordBank.ts.

insert into public.quizzes (id, title, url, icon, color, sort_order)
values
  ('english-word-choice', 'English Word Choice Quiz', 'https://ahmad9077.github.io/english-word-choice-quiz/', '🔠', '#e7f5ef', 50)
on conflict (id) do update set
  title = excluded.title,
  url = excluded.url,
  icon = excluded.icon,
  color = excluded.color,
  sort_order = excluded.sort_order;

insert into public.question_difficulty_profiles (quiz_id, question_key, difficulty, topic_tags)
values
  ('english-word-choice', 'cat', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'dog', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hat', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sun', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'map', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'bed', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'cup', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'box', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'jam', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hop', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'net', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pig', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'rug', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'van', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'web', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'zip', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'ant', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'bus', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'cap', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'dig', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'egg', 28, array['english_word_choice', 'easy', 'length_3', 'double_letter']),
  ('english-word-choice', 'fan', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'gap', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hen', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'ice', 28, array['english_word_choice', 'easy', 'length_3', 'silent_e']),
  ('english-word-choice', 'jet', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'kit', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'log', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'mud', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'nap', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'oak', 28, array['english_word_choice', 'easy', 'length_3', 'vowel_team']),
  ('english-word-choice', 'pan', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'rat', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sad', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'tap', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'vet', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'wax', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'yak', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'zoo', 28, array['english_word_choice', 'easy', 'length_3', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'arm', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'bun', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'cab', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'dam', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'elm', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'fin', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'gem', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hip', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'ivy', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'jug', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'lid', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pod', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sob', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'tag', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'urn', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'wig', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'yam', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'apple', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter', 'silent_e']),
  ('english-word-choice', 'beach', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'brave', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'cabin', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'dance', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'eagle', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'fairy', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'giant', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'happy', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'ivory', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'jewel', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'kneel', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'lemon', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'maple', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'nurse', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'ocean', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'pearl', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'queen', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'river', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'shape', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'tiger', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'viola', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'water', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'xerox', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'yacht', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'zebra', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'acorn', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'blend', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'cloud', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'drill', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'equal', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'flute', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'grace', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'herbs', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'irony', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'llama', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'magic', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'noble', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'orbit', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'petal', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'quill', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'radar', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'scalp', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'vault', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'waltz', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'young', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'frost', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'globe', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'honey', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'image', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'judge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'label', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'melon', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'olive', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'piano', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'quota', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'raven', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'scone', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'torch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'urban', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'vicar', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'wafer', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'xenon', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'yodel', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'zonal', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'chess', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'dream', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'event', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'fable', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'groan', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'hatch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'inlet', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'joker', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'kebab', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'lilac', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'manor', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'notch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'optic', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'plaid', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'quest', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'realm', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'squad', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'trout', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'upset', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'venom', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'wheat', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'yield', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'aloft', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'braid', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'civic', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'delta', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'ember', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'fjord', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'glyph', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'haven', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'icing', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'jumbo', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'knack', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'latch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'marsh', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'nudge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'otter', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'panda', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'quirk', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'ranch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'snout', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'tapir', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'umbra', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'verge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'walrus', 53, array['english_word_choice', 'medium', 'length_6']),
  ('english-word-choice', 'adequate', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'benevolent', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'camouflage', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'democracy', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'eclipse', 78, array['english_word_choice', 'hard', 'length_7', 'silent_e']),
  ('english-word-choice', 'genuine', 78, array['english_word_choice', 'hard', 'length_7', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'hibernate', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'illuminate', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter', 'silent_e']),
  ('english-word-choice', 'jealousy', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'vowel_team']),
  ('english-word-choice', 'knowledge', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'lieutenant', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'mysterious', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'necessary', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter']),
  ('english-word-choice', 'occasion', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'quizzical', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'rendezvous', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'surveillance', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'double_letter', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'tournament', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'unanimous', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'valiant', 78, array['english_word_choice', 'hard', 'length_7', 'vowel_team']),
  ('english-word-choice', 'wonderful', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'xylophone', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'yielding', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'vowel_team']),
  ('english-word-choice', 'zoologist', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'accomplish', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter']),
  ('english-word-choice', 'beneficial', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'dedicated', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'embarrass', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter']),
  ('english-word-choice', 'fascinate', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'government', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'hereditary', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'ingenious', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'jubilation', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'kaleidoscope', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'labyrinth', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'magnificent', 82, array['english_word_choice', 'hard', 'length_11', 'long_word']),
  ('english-word-choice', 'nourishment', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'vowel_team']),
  ('english-word-choice', 'persevere', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'questionnaire', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'double_letter', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'responsible', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'silent_e']),
  ('english-word-choice', 'silhouette', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'trajectory', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'unconscious', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'vowel_team']),
  ('english-word-choice', 'vaccination', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'wavelength', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'exaggerate', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter', 'silent_e']),
  ('english-word-choice', 'yearning', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'vowel_team']),
  ('english-word-choice', 'zealous', 78, array['english_word_choice', 'hard', 'length_7', 'vowel_team']),
  ('english-word-choice', 'apparently', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter']),
  ('english-word-choice', 'brilliant', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'conscience', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'deliberately', 83, array['english_word_choice', 'hard', 'length_12', 'long_word']),
  ('english-word-choice', 'enormous', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'vowel_team']),
  ('english-word-choice', 'flexible', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'silent_e']),
  ('english-word-choice', 'honorable', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'immigrant', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter']),
  ('english-word-choice', 'juvenile', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'silent_e']),
  ('english-word-choice', 'knowledgeable', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'leisurely', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'nuisance', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'oblivious', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'peculiar', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'vowel_team']),
  ('english-word-choice', 'quarantine', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'reluctant', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'sufficient', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'tremendous', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'unforgettable', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'double_letter', 'silent_e']),
  ('english-word-choice', 'vegetarian', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'wilderness', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter']),
  ('english-word-choice', 'expedition', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'zoological', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'abundance', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'bracelet', 79, array['english_word_choice', 'hard', 'length_8', 'long_word']),
  ('english-word-choice', 'candidate', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'dimension', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'equipment', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'forbidden', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter']),
  ('english-word-choice', 'glamorous', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'horizontal', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'legitimate', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'silent_e']),
  ('english-word-choice', 'municipal', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'negotiate', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'omnivore', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'silent_e']),
  ('english-word-choice', 'pastime', 78, array['english_word_choice', 'hard', 'length_7', 'silent_e']),
  ('english-word-choice', 'qualifying', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'raspberry', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter']),
  ('english-word-choice', 'secretary', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'territory', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'double_letter']),
  ('english-word-choice', 'university', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'worthwhile', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'silent_e']),
  ('english-word-choice', 'exemplary', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'yardstick', 80, array['english_word_choice', 'hard', 'length_9', 'long_word']),
  ('english-word-choice', 'zeppelin', 79, array['english_word_choice', 'hard', 'length_8', 'long_word', 'double_letter']),
  ('english-word-choice', 'accomplish_ment', 85, array['english_word_choice', 'hard', 'length_14', 'long_word', 'double_letter']),
  ('english-word-choice', 'bewildered', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'coincidence', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'descendants', 82, array['english_word_choice', 'hard', 'length_11', 'long_word']),
  ('english-word-choice', 'entrepreneur', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'fundamental', 82, array['english_word_choice', 'hard', 'length_11', 'long_word']),
  ('english-word-choice', 'geographical', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'hypothetical', 83, array['english_word_choice', 'hard', 'length_12', 'long_word']),
  ('english-word-choice', 'intellectual', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'justification', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'vowel_team']),
  ('english-word-choice', 'kaleidoscopic', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'vowel_team']),
  ('english-word-choice', 'larynx', 77, array['english_word_choice', 'hard', 'length_6']),
  ('english-word-choice', 'metamorphosis', 84, array['english_word_choice', 'hard', 'length_13', 'long_word']),
  ('english-word-choice', 'neighborhood', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'observatory', 82, array['english_word_choice', 'hard', 'length_11', 'long_word']),
  ('english-word-choice', 'parallelogram', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'double_letter']),
  ('english-word-choice', 'qualification', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'vowel_team']),
  ('english-word-choice', 'rhinoceros', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'sophisticated', 84, array['english_word_choice', 'hard', 'length_13', 'long_word']),
  ('english-word-choice', 'transferable', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'silent_e']),
  ('english-word-choice', 'ultraviolet', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'vowel_team']),
  ('english-word-choice', 'veterinarian', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'watercolor', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'exhilarating', 83, array['english_word_choice', 'hard', 'length_12', 'long_word']),
  ('english-word-choice', 'youthfulness', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'acknowledgement', 86, array['english_word_choice', 'hard', 'length_15', 'long_word']),
  ('english-word-choice', 'approximately', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'double_letter']),
  ('english-word-choice', 'circumstances', 84, array['english_word_choice', 'hard', 'length_13', 'long_word']),
  ('english-word-choice', 'distinguished', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'vowel_team']),
  ('english-word-choice', 'extraordinary', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'vowel_team']),
  ('english-word-choice', 'fluorescent', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'vowel_team']),
  ('english-word-choice', 'gravitational', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'vowel_team']),
  ('english-word-choice', 'humanitarian', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'insignificant', 84, array['english_word_choice', 'hard', 'length_13', 'long_word']),
  ('english-word-choice', 'jurisdiction', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'add', 28, array['english_word_choice', 'easy', 'length_3', 'double_letter']),
  ('english-word-choice', 'age', 28, array['english_word_choice', 'easy', 'length_3', 'silent_e']),
  ('english-word-choice', 'air', 28, array['english_word_choice', 'easy', 'length_3', 'vowel_team']),
  ('english-word-choice', 'ask', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'bit', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'bow', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'boy', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'car', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'cow', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'cry', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'cut', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'day', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'dry', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'dye', 28, array['english_word_choice', 'easy', 'length_3', 'silent_e']),
  ('english-word-choice', 'ear', 28, array['english_word_choice', 'easy', 'length_3', 'vowel_team']),
  ('english-word-choice', 'end', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'eye', 28, array['english_word_choice', 'easy', 'length_3', 'silent_e']),
  ('english-word-choice', 'fly', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'fun', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'get', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'got', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'gum', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hit', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hot', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hug', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'hut', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'ink', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'job', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'joy', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'key', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'law', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'lay', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'let', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'lot', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'mad', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'men', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'mix', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'mop', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'mug', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'net_e', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'new', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'nod', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'now', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'odd', 28, array['english_word_choice', 'easy', 'length_3', 'double_letter']),
  ('english-word-choice', 'old', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'own', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pay', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pen', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pin', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pit', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pop', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pot', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'pup', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'put', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'raw', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'red', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'rid', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'rip', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'rot', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'row', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'rub', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'run', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'saw', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'say', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'set', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'shy', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sip', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sit', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'six', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sky', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sly', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'spy', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'sum', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'ten', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'tie', 28, array['english_word_choice', 'easy', 'length_3', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'tip', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'top', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'toy', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'try', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'tub', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'tug', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'use', 28, array['english_word_choice', 'easy', 'length_3', 'silent_e']),
  ('english-word-choice', 'war', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'was', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'win', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'wit', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'woe', 28, array['english_word_choice', 'easy', 'length_3', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'wow', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'yap', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'yew', 28, array['english_word_choice', 'easy', 'length_3']),
  ('english-word-choice', 'album', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'angle', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'ankle', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'arrow', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'atlas', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'badge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'barge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'basin', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'beast', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'birch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'blade', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'blaze', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'bliss', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'blunt', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'brace', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'brake', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'brook', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'broth', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'budge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'bulge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'bunch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'burst', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'canal', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'canoe', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'cargo', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'cedar', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'chant', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'charm', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'chasm', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'chime', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'choir', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'chore', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'clamp', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'cleft', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'clerk', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'cliff', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'cloak', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'clog', 52, array['english_word_choice', 'medium', 'length_4']),
  ('english-word-choice', 'clump', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'comet', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'comic', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'coral', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'couch', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'court', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'cove', 52, array['english_word_choice', 'medium', 'length_4', 'silent_e']),
  ('english-word-choice', 'crane', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'crawl', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'creek', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'crest', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'crisp', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'croft', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'crust', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'crypt', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'damp', 52, array['english_word_choice', 'medium', 'length_4']),
  ('english-word-choice', 'darts', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'dawn', 52, array['english_word_choice', 'medium', 'length_4']),
  ('english-word-choice', 'decay', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'dense', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'depot', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'derby', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'digit', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'dingo', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'disco', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'ditch', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'dodge', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'dough', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'dowel', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'draft', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'drape', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'drawl', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'dread', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'drove', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'dwarf', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'dwell', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter']),
  ('english-word-choice', 'easel', 52, array['english_word_choice', 'medium', 'length_5', 'vowel_team']),
  ('english-word-choice', 'edible', 53, array['english_word_choice', 'medium', 'length_6', 'silent_e']),
  ('english-word-choice', 'eerie', 52, array['english_word_choice', 'medium', 'length_5', 'double_letter', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'elbow', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'elder', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'elite', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'elven', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'emote', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'envy', 52, array['english_word_choice', 'medium', 'length_4']),
  ('english-word-choice', 'epoxy', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'erode', 52, array['english_word_choice', 'medium', 'length_5', 'silent_e']),
  ('english-word-choice', 'erupt', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'excel', 52, array['english_word_choice', 'medium', 'length_5']),
  ('english-word-choice', 'abbreviation', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'accumulate', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'double_letter', 'silent_e']),
  ('english-word-choice', 'acknowledge', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'silent_e']),
  ('english-word-choice', 'acquaintance', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'architecture', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'silent_e']),
  ('english-word-choice', 'arithmetic', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'astronomical', 83, array['english_word_choice', 'hard', 'length_12', 'long_word']),
  ('english-word-choice', 'atmosphere', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'silent_e']),
  ('english-word-choice', 'autonomous', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'bibliography', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'binoculars', 81, array['english_word_choice', 'hard', 'length_10', 'long_word']),
  ('english-word-choice', 'biochemistry', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'boulevard', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'carnivore', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'silent_e']),
  ('english-word-choice', 'celestial', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'chronological', 84, array['english_word_choice', 'hard', 'length_13', 'long_word']),
  ('english-word-choice', 'civilization', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'vowel_team']),
  ('english-word-choice', 'collaborate', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'double_letter', 'silent_e']),
  ('english-word-choice', 'commemorate', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'double_letter', 'silent_e']),
  ('english-word-choice', 'communicate', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'double_letter', 'silent_e']),
  ('english-word-choice', 'concentrate', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'silent_e']),
  ('english-word-choice', 'consecutive', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'silent_e']),
  ('english-word-choice', 'constellation', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'double_letter', 'vowel_team']),
  ('english-word-choice', 'courageous', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'vowel_team']),
  ('english-word-choice', 'curiosity', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'cylinder', 79, array['english_word_choice', 'hard', 'length_8', 'long_word']),
  ('english-word-choice', 'deciduous', 80, array['english_word_choice', 'hard', 'length_9', 'long_word', 'vowel_team']),
  ('english-word-choice', 'declaration', 82, array['english_word_choice', 'hard', 'length_11', 'long_word', 'vowel_team']),
  ('english-word-choice', 'disadvantage', 83, array['english_word_choice', 'hard', 'length_12', 'long_word', 'silent_e']),
  ('english-word-choice', 'disappearance', 84, array['english_word_choice', 'hard', 'length_13', 'long_word', 'double_letter', 'silent_e', 'vowel_team']),
  ('english-word-choice', 'discourage', 81, array['english_word_choice', 'hard', 'length_10', 'long_word', 'silent_e', 'vowel_team'])
on conflict (quiz_id, question_key) do update set
  difficulty = excluded.difficulty,
  topic_tags = excluded.topic_tags;

select
  quiz_id,
  count(*) as seeded_questions,
  min(difficulty) as min_difficulty,
  max(difficulty) as max_difficulty
from public.question_difficulty_profiles
where quiz_id = 'english-word-choice'
group by quiz_id;
