-- Approved production seed for Arabic Phonics / صدى الحروف.
-- Generated by scripts/generate-hub-seed.mjs and approved for release on 2026-08-14.
-- Intentionally creates no quiz_assignments.

begin;

insert into public.quizzes (id, title, url, icon, color, sort_order)
values (
  'arabic-phonics',
  'صدى الحروف',
  'https://ahmad9077.github.io/arabic-phonics-quiz/',
  'أ',
  '#efe8ff',
  70
)
on conflict (id) do update set
  title = excluded.title,
  url = excluded.url,
  icon = excluded.icon,
  color = excluded.color,
  sort_order = excluded.sort_order;

insert into public.question_difficulty_profiles (
  quiz_id,
  question_key,
  difficulty,
  topic_tags,
  skill_tags
)
values
  ('arabic-phonics', 'alif:isolated', 30, array['arabic_phonics', 'form_isolated', 'family_alif_line', 'joining_right'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'alif:final', 50, array['arabic_phonics', 'form_final', 'family_alif_line', 'joining_right'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'beh:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'beh:initial', 70, array['arabic_phonics', 'form_initial', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'beh:final', 56, array['arabic_phonics', 'form_final', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'teh:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'teh:initial', 70, array['arabic_phonics', 'form_initial', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'teh:final', 56, array['arabic_phonics', 'form_final', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'theh:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'theh:initial', 70, array['arabic_phonics', 'form_initial', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'theh:final', 56, array['arabic_phonics', 'form_final', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'jeem:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'jeem:initial', 70, array['arabic_phonics', 'form_initial', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'jeem:final', 56, array['arabic_phonics', 'form_final', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'hah:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'hah:initial', 70, array['arabic_phonics', 'form_initial', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'hah:final', 56, array['arabic_phonics', 'form_final', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'khah:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'khah:initial', 70, array['arabic_phonics', 'form_initial', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'khah:final', 56, array['arabic_phonics', 'form_final', 'family_hah_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'dal:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_dal_hook', 'joining_right'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'dal:final', 56, array['arabic_phonics', 'form_final', 'family_dal_hook', 'joining_right'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'thal:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_dal_hook', 'joining_right'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'thal:final', 56, array['arabic_phonics', 'form_final', 'family_dal_hook', 'joining_right'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'reh:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_reh_tail', 'joining_right'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'reh:final', 56, array['arabic_phonics', 'form_final', 'family_reh_tail', 'joining_right'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'zain:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_reh_tail', 'joining_right'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'zain:final', 56, array['arabic_phonics', 'form_final', 'family_reh_tail', 'joining_right'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'seen:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_seen_teeth', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'seen:initial', 70, array['arabic_phonics', 'form_initial', 'family_seen_teeth', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'seen:final', 56, array['arabic_phonics', 'form_final', 'family_seen_teeth', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'sheen:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_seen_teeth', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'sheen:initial', 70, array['arabic_phonics', 'form_initial', 'family_seen_teeth', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'sheen:final', 56, array['arabic_phonics', 'form_final', 'family_seen_teeth', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'sad:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_sad_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'sad:initial', 70, array['arabic_phonics', 'form_initial', 'family_sad_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'sad:final', 56, array['arabic_phonics', 'form_final', 'family_sad_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'dad:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_sad_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'dad:initial', 70, array['arabic_phonics', 'form_initial', 'family_sad_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'dad:final', 56, array['arabic_phonics', 'form_final', 'family_sad_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'tah:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_tah_pole', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'tah:initial', 70, array['arabic_phonics', 'form_initial', 'family_tah_pole', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'tah:final', 56, array['arabic_phonics', 'form_final', 'family_tah_pole', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'zah:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_tah_pole', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'zah:initial', 70, array['arabic_phonics', 'form_initial', 'family_tah_pole', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'zah:final', 56, array['arabic_phonics', 'form_final', 'family_tah_pole', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'ain:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_ain_eye', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'ain:initial', 70, array['arabic_phonics', 'form_initial', 'family_ain_eye', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'ain:final', 56, array['arabic_phonics', 'form_final', 'family_ain_eye', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'ghain:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_ain_eye', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'ghain:initial', 70, array['arabic_phonics', 'form_initial', 'family_ain_eye', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'ghain:final', 56, array['arabic_phonics', 'form_final', 'family_ain_eye', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'feh:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_feh_loop', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'feh:initial', 70, array['arabic_phonics', 'form_initial', 'family_feh_loop', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'feh:final', 56, array['arabic_phonics', 'form_final', 'family_feh_loop', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'qaf:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_feh_loop', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'qaf:initial', 70, array['arabic_phonics', 'form_initial', 'family_feh_loop', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'qaf:final', 56, array['arabic_phonics', 'form_final', 'family_feh_loop', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'kaf:isolated', 30, array['arabic_phonics', 'form_isolated', 'family_kaf', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'kaf:initial', 64, array['arabic_phonics', 'form_initial', 'family_kaf', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'kaf:final', 50, array['arabic_phonics', 'form_final', 'family_kaf', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'lam:isolated', 30, array['arabic_phonics', 'form_isolated', 'family_lam', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'lam:initial', 64, array['arabic_phonics', 'form_initial', 'family_lam', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'lam:final', 50, array['arabic_phonics', 'form_final', 'family_lam', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'meem:isolated', 30, array['arabic_phonics', 'form_isolated', 'family_meem', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'meem:initial', 64, array['arabic_phonics', 'form_initial', 'family_meem', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'meem:final', 50, array['arabic_phonics', 'form_final', 'family_meem', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'noon:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'noon:initial', 70, array['arabic_phonics', 'form_initial', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'noon:final', 56, array['arabic_phonics', 'form_final', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'heh:isolated', 30, array['arabic_phonics', 'form_isolated', 'family_heh', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'heh:initial', 64, array['arabic_phonics', 'form_initial', 'family_heh', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'heh:final', 50, array['arabic_phonics', 'form_final', 'family_heh', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'waw:isolated', 30, array['arabic_phonics', 'form_isolated', 'family_waw', 'joining_right'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'waw:final', 50, array['arabic_phonics', 'form_final', 'family_waw', 'joining_right'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'yeh:isolated', 36, array['arabic_phonics', 'form_isolated', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'base_letter']),
  ('arabic-phonics', 'yeh:initial', 70, array['arabic_phonics', 'form_initial', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form']),
  ('arabic-phonics', 'yeh:final', 56, array['arabic_phonics', 'form_final', 'family_beh_bowl', 'joining_dual'], array['sound_to_symbol', 'joining_form'])
on conflict (quiz_id, question_key) do update set
  difficulty = excluded.difficulty,
  topic_tags = excluded.topic_tags,
  skill_tags = excluded.skill_tags,
  updated_at = now();

do $$
begin
  if (select count(*) from public.question_difficulty_profiles where quiz_id = 'arabic-phonics') <> 78 then
    raise exception 'Arabic Phonics profile count must be exactly 78';
  end if;
end
$$;

commit;

select
  quiz_id,
  count(*) as seeded_questions,
  min(difficulty) as min_difficulty,
  max(difficulty) as max_difficulty
from public.question_difficulty_profiles
where quiz_id = 'arabic-phonics'
group by quiz_id;
